-- Questões ENARE 2024
-- Gerado em: 2026-02-09T17:31:57.812Z
-- Total: 47 questões

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Pneumologia', 'media', 'Em relação ao tema paraneoplásicas relacionadas manifestações ao câncer de pulmão, assinale a alternativa INCORRETA.', 'A neuropatia periférica aguda é mais prevalente como sindrome paraneoplásica pulmonar no subtipo não pequenas células.', 'Síndrome de Lambert-Eaton está associada ao quadro de síndrome miastênica, frequentemente associado ao carcinoma indiferenciado de pequenas células.', 'A síndrome de Cushing foi descrita como secreção ectópica do ACTH pelo tumor do pulmão, sendo frequente no carcinoma de pequenas células.', 'A SIADH (Síndrome da Secreção Inadequada do Hormônio Antidiurético) está correlacionada ao carcinoma indiferenciado de pequenas células.', 'A osteoartropatia pulmonar hipertrófica pode preceder os sintomas pulmonares do câncer de pulmão em meses.', 'A');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Dermatologia', 'facil', 'Qual é a coloração utilizada na baciloscopia para investigação de hanseniase?', 'Tinta da China.', 'Ziehl-Neelsen.', 'Vermelho congo.', 'Azul da Prússia.', 'Grocott', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Todas as áreas', 'Bioética', 'facil', 'Um médico assistente é o responsável por comunicar ao paciente que os resultados dos exames mostraram o diagnóstico de câncer metastático. Assinale a alternativa que aborda de forma adequada a comunicação de más notícias como nesse caso.', 'O paciente precisa ser informado a qualquer custo naquele momento, mesmo que ele deixe claro que não deseja saber.', 'Deve-se deixar claro que não há mais nada a ser feito pelo paciente.', 'A comunicação deve ser rápida e objetiva, sem espaço para dúvidas.', 'Deve-se utilizar termos técnicos independente da compreensão do paciente, garantindo a passagem de informações corretas.', 'Deve-se usar palavras adequadas ao vocabulário do paciente, formular frases curtas e perguntar, com certa frequência, como o paciente está e o que está entendendo.', 'E');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Neurologia', 'media', 'Homem, 24 anos, sem comorbidades conhecidas, sob estresse emocional intenso relacionado ao preparo para uma prova de um concurso público, procurou o pronto atendimento com queixa principal de que o lado direito do rosto não se mexia havia 1 dia. Ao exame físico, apresentava paralisia em hemiface superior e inferior à direita, paralisia da pálpebra superior direita que levava à dificuldade de fechar o olho e piscar, além de desvio da rima labial para o lado esquerdo. As pupilas estavam isocóricas e fotorreagentes, e a força estava preservada (grau V) em membros superiores e inferiores bilaterais. De acordo com o caso clínico apresentado, qual é a principal hipótese diagnóstica?', 'Paralisia de Todd.', 'Acidente vascular encefálico.', 'Sindrome de Claude Bernard-Horner.', 'Paralisia de Bell.', 'Hemorragia subaracnoidea.', 'D');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Reumatologia', 'media', 'Assinale a alternativa que apresenta corretamente as principais manifestações extra-articulares da artrite psoriática.', 'Pneumopatia intersticial padrão não específico; esclerodactilia; microstomia, fenômeno de Raynaud.', 'Entesite; pneumopatia intersticial usual: hipertensão pulmonar; mãos de mecânico.', 'Sinal do Coldre; heliotropo; dactilite; ganglionopatia.', 'Doença inflamatória intestinal; pneumopatia intersticial usual; xeroftalmia; fenômeno de Raynaud.', 'Doença inflamatória intestinal; uveíte; dactilite; entesite.', 'A');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Pneumologia', 'media', 'Um médico, trabalhando em uma unidade de pronto atendimento, atende um paciente de 70 anos com queixa de febre de início há 4 dias, acompanhada de tosse produtiva e astenia. O paciente é diabético e hipertenso, encontra-se consciente e orientado, porém, no momento, está com a visão prejudicada, devido à cirurgia recente de correção de catarata. Ele não tem tomado as medicações de uso contínuo por não estar conseguindo identificá-las. Seu filho, que mora há 450Km de distância, chegará em 2 dias para poder acompanhá-lo. Ao exame físico, apresenta frequência respiratória de 24 irpm, pressão arterial de 100x64 mmHg, exame laboratorial: ureia 45 mg/dl e creatinina 0,6 mg/dL. Diante do exposto, qual seria a conduta adequada?', 'Internar o paciente para início do tratamento, por possuir 4 pontos no escore de prognóstico "CURB-65."', 'O paciente pode realizar o tratamento ambulatorial por possuir apenas 1 ponto no escore de prognóstico "CURB-65".', 'Apesar de o paciente ter somente 1 ponto no escore de prognóstico "CURB-65", devido às comorbidades e ao seu contexto social, a conduta mais adequada é interná-lo para o tratamento.', 'O paciente pode realizar o tratamento ambulatorial por possuir apenas 2 pontos no escore de prognóstico "CURB-65".', 'Internar o paciente para início do tratamento, por possuir 3 pontos no escore de prognóstico "CURB-65."', 'C');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Endocrinologia', 'facil', 'Paciente do sexo feminino, 56 anos, em pós-operatório de tireoidectomia radical, deu entrada no pronto atendimento com queixa de formigamento em membros superiores e tremores, associados a sudorese. No exame físico, são encontrados sinais de Trousseau e Chvostek positivos. Considerando o antecedente da paciente, qual eletrólito pode estar em níveis alterados e que poderia explicar a clínica e os achados no exame físico?', 'Cálcio.', 'Sódio.', 'Potássio.', 'Magnésio.', 'Cloro.', 'A');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Cardiologia', 'media', 'Uma mulher de 58 anos apresentou-se à sala de emergência com palpitações intensas, dor torácica e dispneia. Ela relatou que as palpitações começaram repentinamente enquanto estava em repouso em casa. Não havia histórico prévio de arritmias. Sinais vitais: frequência cardíaca estimada em cerca de 150 bpm; pressão arterial: 80/50 mmHg. Assinale a alternativa que apresenta o diagnóstico e a conduta adequada para esse caso.', 'Taquicardia supraventricular / Sedação leve e cardioversão química.', 'Fibrilação atrial / Sedação leve e cardioversão elétrica.', 'Flutter atrial / Desfibrilação.', 'Taquicardia sinusal / Conduta expectante.', 'Fibrilação atrial / Sedação leve e cardioversão química.', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Todas as áreas', 'Ética Médica', 'facil', 'De acordo com o tema "publicidade médica", é correto afirmar que', 'é vedado divulgar fora do meio científico processo de tratamento ou descoberta cujo valor ainda não esteja expressamente reconhecido cientificamente por órgão competente.', 'é permitida a participação e divulgação de médicos, em qualquer meio de comunicação de massa, mesmo que não tenha caráter exclusivo de esclarecimento e educação da sociedade.', 'é autorizado participar de anúncios de empresas comerciais, qualquer que seja sua natureza, valendo-se de sua profissão.', 'há dispensa da apresentação do número no Conselho Regional de Medicina e do Registro de Qualificação de Especialista (RQE) quando anunciar a especialidade em anúncios profissionais.', 'é liberado o anúncio de títulos científicos mesmo que não possa comprovar a especialidade ou área de atuação com registro no Conselho Regional de Medicina.', 'A');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Pneumologia', 'media', 'Paciente do sexo masculino, 73 anos, apresentou desconforto respiratório progressivo na última semana e foi avaliado no pronto-socorro. Ao exame físico, apresentava, na ausculta pulmonar, murmúrio vesicular abolido em 2/3 inferiores, tendo sido confirmado derrame pleural moderado por radiografia de tórax. Após ser avaliado pela cirurgia torácica, optou-se por toracocentese de alívio e diagnóstica. Os exames séricos do paciente eram: Proteína total 3,8 g/dl, DHL 154 U/L. A rotina laboratorial de líquido pleural: Proteína total 1,7 g/dl, DHL 60 U/L. — Observação: Desidrogenase láctica (DHL) valores séricos normais de referência 120 a 246 U/L. Após análise dos resultados dos exames séricos e da rotina do líquido pleural do paciente, são aplicados os critérios de Light. Assinale a alternativa correta em relação a esse caso.', 'Os resultados da análise indicam características de transudato, e insuficiência cardíaca poderia ser uma das hipóteses diagnósticas.', 'A relação entre LDH do líquido pleural/nível sérico preenche um dos critérios de Light, caraterístico de exsudato.', 'Os resultados da análise indicam características de exsudato pelos critérios de Light, e pneumonia bacteriana é uma das hipóteses diagnósticas.', 'Para transudato, é necessário preencher pelo menos dois dos critérios de Light.', 'Um dos critérios de Light é que o DHL do líquido pleural seja > 1/3 do valor do limite superior sérico.', 'A');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Todas as áreas', 'Emergência', 'facil', 'Diante de um atendimento a um paciente em parada cardiorrespiratória, o líder precisa conduzir a equipe que está realizando a Reanimação Cardiopulmonar (RCP). Qual é a maneira de comunicação mais apropriada entre o líder e a equipe nessa situação?', 'Apenas o líder da equipe possui a competência necessária para verbalizar informações, devendo o restante da equipe permanecer em silêncio durante todo o atendimento.', 'O líder deve transmitir mensagens simultâneas a cada membro da equipe para que sejam evitados atos de procrastinação e a situação possa ser revertida o mais rápido possível.', 'O líder deve transmitir uma mensagem, ordem ou atribuição a um membro da equipe; solicitar uma resposta clara e contato visual do membro da equipe para garantir que tenha entendido a mensagem; confirmar que o membro da equipe concluiu a tarefa, antes de lhe atribuir outra tarefa.', 'O líder deve elevar o tom de voz ao perceber que um dos membros da equipe não compreendeu a ordem dada, a fim de que tal atitude não se repita.', 'É necessário que o líder reconheça sua equipe com elogios, como forma de incentivá-la quando o atendimento é bem sucedido, bem como repreender em alto tom de voz ao perceber quaisquer falhas durante o atendimento.', 'C');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Cardiologia', 'media', 'Em relação ao uso de trombolíticos em paciente com infarto agudo do miocárdio com supra de ST no eletrocardiograma, é considerado(a) contraindicação absoluta', 'uso crônico de AAS 100 mg diário.', 'trauma cranioencefálico importante nos últimos 3 meses.', 'histórico de úlcera péptica mesmo sem evidência de sangramento ativo.', 'acidente vascular encefálico isquêmico há 1 ano.', 'gestação.', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Gastroenterologia', 'media', 'Homem, 46 anos, hipertenso e etilista, comparece à emergência médica após hematêmese e confusão mental aguda. Apresenta-se, ao exame físico, ictérico, confuso, desorientado, sarcopênico e hipotenso. Após estabilização clínica inicial, foi submetido a exames laboratoriais que evidenciaram: INR 3.2; Albumina 1.8 g/dL; Bilirrubinas totais 9.5 mg/dL e Creatinina de 4.2 mg/dL. Assinale a alternativa que NÃO contribui, dentro do caso apresentado, para a classificação de Child-Pugh do paciente.', 'INR.', 'Albumina.', 'Bilirrubinas.', 'Creatinina.', 'Grau de Encefalopatia.', 'D');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Psiquiatria', 'media', 'Sobre delirium tremens, assinale a alternativa correta.', 'Contenção mecânica imediata e administração de haloperidol intramuscular fazem parte do manejo. O uso de benzodiazepínicos é contraindicado devido ao risco de piora aguda do delirium tremens.', 'O uso de fenitoina parenteral, a "hidantalização", deve ser feito de rotina, sendo eficaz no controle de crises convulsivas.', 'Monitorar, corrigir possíveis distúrbios hidroeletrolíticos, realizar hidratação vigorosa, iniciar benzodiazepínico e profilaxia para encefalopatia de Wernicke-Korsakoff podem ser ações necessárias para o manejo adequado.', 'A administração de clorpromazina e outros neurolépticos sedativos de baixa potência para controle de agitação são a primeira escolha em relação ao uso de haloperidol.', 'As manifestações geralmente ocorrem antes das primeiras vinte e quatro horas após a última ingesta de bebida alcóolica.', 'C');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Pneumologia', 'facil', 'Dentre as alternativas a seguir, qual apresenta o agente infeccioso bacteriano mais comum na pneumonia adquirida na comunidade?', 'Streptococcus pneumoniae.', 'Mycoplasma pneumoniae.', 'Streptococcus aureus.', 'Chlamydia pneumoniae.', 'Pseudomonas aeruginosa.', 'A');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Nefrologia', 'media', 'Mulher de 66 anos acompanhada da filha, foi encaminhada para Nefrologia pela unidade básica de saúde (UBS) devido à alteração no exame de creatinina. Trouxe exames laboratoriais que evidenciavam: Hb8,7g/L; Creatinina 2,8mg/dL; Ureia 32 mg/dL; Gasometria arterial pH 7,3; Bicarbonato 18 mmol/L; Na 140 mmol/L; K 5,2 mmol/L. Um exame realizado há 4 anos já evidenciavam creatinina sérica basal de 2,3 mg/dL. O peso da paciente é de 56kg. Conforme o caso apresentado, assinale a alternativa correta.', 'Está contraindicada vacina contra hepatite B para essa paciente.', 'O clearance de creatinina pela equação de Cockcroft-Gault é de 20ml/min. A paciente está em estágio 3 de doença renal crônica.', 'Essa paciente não deveria ter sido encaminhada para a nefrologia, devendo ser acompanhada somente em UBS.', 'O tratamento para essa paciente deve ser classificado como conservador, pois ela está entre os estágios 1 e 3 de doença renal crônica.', 'O clearance de creatinina pela equação de Cockcroft-Gault é de 17ml/min. A paciente está em estágio 4 de doença renal crônica.', 'E');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Neurologia', 'facil', 'É considerada uma manifestação clínica comum da doença de Parkinson a', 'estabilidade postural.', 'hipercinesia.', 'fasciculação.', 'hipermobilidade.', 'rigidez em roda dentada.', 'E');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Infectologia', 'media', 'Em relação á reação de Jarisch-Harxheimer, assinale a alternativa correta.', 'Ocorre no final do tratamento de sífilis, no qual o paciente pode apresentar exacerbação das lesões cutâneas, com eritema, dor ou prurido.', 'Cursa com febre, dor de cabeça, sudores, calafrios e tremores, sendo necessária a suspensão imediata do tratamento devido ao alto risco de reação anafilática.', 'É uma reação alérgica grave á penicilina com alto risco de reação anafilática e necessidade de administração de adrenalina intramuscular profilática.', 'Ocorre no início do tratamento da sífilis em resposta ao derrame de proteínas e de outras estruturas dos treponemas mortos pela penicilina na corrente sanguínea.', 'Também é conhecida como síndrome de Stevens-Johnson.', 'D');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Endocrinologia', 'media', 'Assinale a alternativa correta que apresenta uma medicação osteoformadora indicada no tratamento da osteoporose de alto ou muito alto risco de fraturas.', 'Alendronato.', 'Denosumabe.', 'Ácido Zoledrônico.', 'Teriparatida.', 'Raloxifeno.', 'D');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Todas as áreas', 'Bioética', 'facil', 'Durante atendimento de um paciente portador de artrite reumatoide, ele demonstra bastante resistência para realizar o tratamento com medicações injetáveis. Diante desse cenário, qual atitude é a mais adequada?', 'Ameaçar abandonar o acompanhamento, caso o paciente não aceite a medicação indicada.', 'Respeitar o direito do paciente de decidir livremente sobre seu tratamento, salvo em risco iminente de morte.', 'Prescrever o que há de melhor para o paciente, independentemente das preferências individuais dele.', 'Oferecer apenas o tipo de tratamento que julgar melhor, não sendo necessário utilizar todos os meios disponíveis de promoção de saúde e de tratamento.', 'Exagerar a gravidade do diagnóstico ou do prognóstico e complicar a terapêutica, para que o paciente entenda que a medicação injetável é extremamente necessária.', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Todas as áreas', 'Ética Médica', 'facil', 'Um paciente encontra-se internado devido a uma infecção de partes moles associada à lesão vegetante, friável e ulcerativa em perna, com crescimento há 2 meses, sem melhora. É solicitada uma avaliação médica para biópsia. A enfermeira do setor do paciente liga para o médico, que se encontra em outro setor do hospital atendendo a um segundo paciente, e questiona se ela pode ir realizando a biópsia enquanto ele não chega. Quanto a essa situação, assinale a alternativa correta.', 'O médico deve permitir que a enfermeira realize a biópsia, tendo em vista que será de fácil execução e que poderá agilizar o diagnóstico, já que provavelmente é compatível com um câncer de pele.', 'O médico deve permitir que a enfermeira realize a biópsia, porém deve orientá-la sobre execução do procedimento, passo a passo, antes de iniciá-lo.', 'O médico deve solicitar à enfermeira que aguarde a sua chegada para iniciar a realização da biópsia, permitindo que ela a realize para ampliar seu conhecimento prático.', 'O médico deve pedir à enfermeira que não realize a biópsia nesse momento, porque, primeiro, deve ser avaliada a existência de outras lesões que necessitam de biópsia a fim de que ela realize todas em um mesmo tempo.', 'O médico deve pedir à enfermeira que não realize a biópsia, pois esse tipo de procedimento é considerado um ato privativo do médico.', 'E');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Gastroenterologia', 'facil', 'Um paciente com obstrução e infecção das vias biliares apresenta a chamada tríade de Charcot, a qual é caracterizada por:', 'icterícia, hipotensão e confusão mental.', 'dor em hipocôndrio direito, icterícia e hipotensão.', 'febre, hipotensão e icterícia.', 'icterícia, dor em hipocôndrio direito e febre.', 'febre, icterícia e confusão mental.', 'D');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Clínica Médica', 'Gastroenterologia', 'media', 'Sobre doença de Crohn e colite ulcerativa, informe se é verdadeiro (V) ou falso (F) o que se afirma a seguir e assinale a alternativa com a sequência correta. ( ) O tabagismo parece conferir um efeito protetor na colite ulcerativa. ( ) A lesão mais característica da colite ulcerativa é o abscesso das criptas de Lieberkühn. ( ) Uma característica histológica importante da doença de Crohn é o granuloma não caseoso, um agregado de histiócitos epitelioides circundados por neutrófilos e células gigantes. ( ) O paciente com doença de Crohn pode desenvolver fístulas entre o intestino e qualquer outro órgão intra-abdominal, a maioria delas envolve o intestino delgado.', 'V-V-F-V.', 'F-V-F-V.', 'V-V-V-V.', 'V-V-F-F.', 'F-V-V-F.', 'C');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Gastroenterologia', 'media', 'O médico de um paciente cirrótico está verificando a possibilidade de uma cirurgia hepática para esse paciente, porém, para isso, quer primeiro verificar o escore de Child-Pugh, já que este possui correlação com a sobrevida do paciente. Nesse sentido, o paciente apresenta os seguintes exames: bilirrubina de 2,5 mg/dL; albumina de 2,6 g/dL; tempo de trombina de 2 segundos; nenhuma ascite ou encefalopatia. Diante desses resultados, qual é a classificação de Child-Pugh desse paciente e sua chance de sobrevida?', 'Child-Pugh A/ Sobrevida alta.', 'Child-Pugh B / Sobrevida intermediária.', 'Child-Pugh C/ Sobrevida baixa.', 'Child-Pugh D / Sobrevida alta.', 'Child-Pugh C/ Sobrevida intermediária.', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Gastroenterologia', 'media', 'Um paciente de 45 anos teve uma pancreatite aguda e, após 6 semanas, passou a notar dor abdominal persistente, saciedade precoce, náusea e perda de peso. Ao procurar o serviço médico, foram verificados níveis elevados das enzimas pancreáticas e uma lesão cística de aproximadamente 8 cm em cauda do pâncreas, em contato com a parede gástrica. Qual é o provável diagnóstico e a conduta mais adequada nesse caso?', 'Trata-se provavelmente de necrose pancreática que deve ser tratada com antibióticos de amplo espectro como o meropenem.', 'Trata-se provavelmente de um pseudocisto pancreático que deve ser tratado com antibióticos de amplo espectro como o meropenem.', 'Trata-se provavelmente de pseudocisto pancreático e pode-se tentar uma drenagem endoscópica transgástrica.', 'Trata-se provavelmente de necrose pancreática que deve ser tratada de maneira expectante, com indicação de intervenção cirúrgica se o paciente apresentar febre.', 'Trata-se provavelmente de pseudocisto pancreático que deve ser tratado com abordagem cirúrgica por laparotomia.', 'C');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Obstetrícia', 'media', 'Uma paciente gestante de 25 semanas apresenta dor em região de flanco direito há 1 dia, associada a náuseas e vômitos. No hemograma, apresenta uma leucocitose de 11.500 (VR = 10.000). Quanto a esse caso, é correto afirmar que', 'se deve fazer uma ultrassonografia abdominal devido à suspeita de apendicite aguda e, caso necessário, tomografia para melhor visualização do apêndice.', 'há suspeita de apendicite aguda, devido à localização da dor (apêndice deslocado cefalicamente). Uma ultrassonografia de abdome pode visualizar o apêndice e ajudar a esclarecer o diagnóstico.', 'pode se tratar apenas de uma intercorrência da gestação, como dor do ligamento redondo. Para melhor esclarecimento do caso, deve-se solicitar uma ressonância abdome, ultrassonografia não é recomendada nessa idade gestacional.', 'há grandes chances de ser uma apendicite aguda, já que a paciente tem dor em flanco direito (apêndice deslocado cefalicamente) e tem leucocitose, sinal de que há um processo inflamatório agudo vigente.', 'se trata de uma provável colecistite, devido à topografia da dor associada à leucocitose, que favorece processo inflamatório agudo.', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Gastroenterologia', 'media', 'No caso de um paciente que realizou gastrectomia parcial e tem apresentado, 20 minutos após a ingesta alimentar, sintomas como náuseas, vômitos, sensação de plenitude gástrica, diarreia explosiva, palpitações e taquicardia, qual é o provável diagnóstico e a orientação que o médico deve fornecer para a melhora dos sintomas?', 'Dumping tardio / Orientar a evitar hipoglicemia, ingerindo maiores quantidades de alimentos com açúcar em um menor intervalo de tempo.', 'Síndrome da alça aferente / Orientar o paciente a provocar vômitos quando tiver os sintomas de plenitude gástrica, pois geralmente gera um alívio imediato dos sintomas.', 'Gastrite alcalina de refluxo / Orientar o paciente a utilizar inibidor de bomba de prótons a cada 12 horas e evitar a ingestão de alimentos ácidos.', 'Atonia gástrica / Utilizar pró-cinéticos como a metoclopramida e fazer a ingestão de várias refeições com menores quantidades de alimentos.', 'Dumping precoce / Orientar a evitar alimentos que contenham grande quantidade de açúcar, realizar pequenas refeições com proteinas e gorduras em menor intervalo de tempo e separar os líquidos dos sólidos durante as refeições.', 'E');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Oncologia', 'media', 'Assinale a alternativa que apresenta alguns dos principais genes mutados que contribuem para o surgimento do câncer colorretal hereditário e um dos fatores que pode contribuir para a prevenção do câncer colorretal esporádico.', 'BRCA 1 e BRCA 2 / Consumo diário de grandes quantidades de proteína.', 'VHL e KRAS / Ingestão diária de ômega 3.', 'BRAF e MEN1 / Dieta restrita em carnes vermelhas e gorduras.', 'APC e MSH2 / Atividade física regular.', 'BRCA 2 e p53 / Alimentação rica em frutas e vegetais.', 'D');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Todas as áreas', 'Ética Médica', 'facil', 'Um médico está realizando uma live (transmissão ao vivo) para alunos de medicina dentro do centro cirúrgico e, sem avisar, adentra a sala de um segundo médico (cirurgião) durante a realização gastroduodenopancreatectomia, solicitando que o colega descreva e demonstre os passos dessa cirurgia. Assinale a melhor conduta e a justificativa do segundo cirurgião diante dessa situação.', 'Tendo vista o aprendizado que os expectadores terão sobre uma cirurgia não tão comum, o cirurgião deve aceitar a proposta e demostrar a cirurgia durante a live.', 'O cirurgião deve aceitar a proposta e, posteriormente, informar ao paciente que foi realizada a live com o intuito de contribuir para o avanço da medicina.', 'O cirurgião não deve aceitar a proposta devido à proibição do Conselho Federal de Medicina quanto à realização de lives realizadas por médicos.', 'O cirurgião deve aceitar a proposta desde que, posteriormente, o paciente seja compensado monetariamente pelo uso de sua imagem.', 'O cirurgião não deve aceitar a proposta, pois a imagem do paciente não deve ser exposta na mídia, especialmente sem sua prévia autorização.', 'E');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Dermatologia', 'media', 'Um paciente de 37 anos, com pele e olhos claros e história familiar de melanoma, possui uma lesão pigmentada em região da mão esquerda de, aproximadamente, 1 cm. Nesse caso, a melhor conduta a ser seguida para esse paciente é realizar', 'Biópsia incisional da lesão e sutura em pontos simples com fio absorvível.', 'Tratamento precoce, com resseção da lesão com margens amplas devido ao histórico familiar, com sutura contínua após ressecção.', 'Biópsia excisional da lesão e sutura em pontos simples com fio inabsorvível.', 'Ressecção da lesão com margem de 1 cm devido à alta suspeita de melanoma e sutura contínua com fio inabsorvível.', 'Biópsia com 5 mm de margem e enxerto em mão com sutura contínua.', 'C');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Todas as áreas', 'Bioética', 'media', 'Um paciente que mora sozinho, está, no momento, acompanhado de um familiar que reside em uma cidade distante e permite que o médico lhe forneça o resultado de uma biópsia realizada de algumas lesões da pele. O diagnóstico é sarcoma de Kaposi. Esse familiar questiona o médico, junto ao paciente, sobre a doença e se sente surpreso, dizendo que o paciente sempre foi saudável e não possuía nenhuma doença prévia. Diante dessa situação, assinale a alternativa correta.', 'Deve-se informar ao familiar, junto ao paciente, que o Kaposi é frequentemente observado em pacientes com Imunodeficiência Adquirida (AIDS) e, portanto, deve ser investigada a presença da doença imediatamente.', 'Deve-se informar ao familiar que o Kaposi é uma neoplasia maligna de tecidos moles de baixo grau, porém não se deve fornecer mais informações sem o consentimento do paciente, pois ele pode ter o diagnóstico de AIDS em sigilo, já que o Kaposi é frequentemente associado à Imunodeficiência Adquirida.', 'Já que o paciente permitiu fornecer o resultado da biópsia, é possível inferir que o familiar é próximo e deve-se orientar os dois sobre a possibilidade de o paciente também ter AIDS, já que o Kaposi é frequentemente associado a essa patologia.', 'Deve-se informar ao paciente e ao familiar que o Kaposi é uma neoplasia maligna associada à AIDS, já que, nesse momento, o familiar é representante legal do paciente e não é preciso manter sigilo profissional em relação a esse familiar.', 'Deve-se informar ao paciente e ao familiar sobre o Kaposi, sobre a possível associação da doença com a AIDS e que o paciente pode estar infectado com o vírus, já que, nessa ocasião de risco a um terceiro (possibilidade de transmissão da doença por contato entre eles), o acompanhante também deve ter acesso a essas informações.', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Todas as áreas', 'Bioética', 'facil', 'Um paciente de 82 anos, lúcido, realizará uma cirurgia eletiva para câncer de reto. Sabendo da grande chance de o paciente precisar de um estoma, os familiares solicitam ao médico que não revele ao paciente essa informação antes do procedimento, pois referem que ele não irá aceitar a cirurgia. Assinale a alternativa que apresenta a melhor conduta diante desse caso.', 'Não revelar ao paciente a possibilidade do estoma, pois essa informação pode prejudicar psicologicamente o paciente.', 'Informar o paciente sobre a cirurgia, porém não sobre o estoma, deixando a explicação apenas para depois do procedimento, com a finalidade de que ele não deixe de fazer a cirurgia, já que esta é fundamental para seu tratamento.', 'Revelar ao paciente apenas as informações que os familiares julgarem necessárias.', 'Informar o paciente sobre a possibilidade do estoma apenas se ele questionar sobre tal assunto.', 'Informar o paciente sobre a possibilidade do estoma, independente da vontade dos familiares, já que o paciente é lúcido e é dever do médico informar os riscos do tratamento ao paciente.', 'E');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', NULL, 'media', 'Os tecidos tentam restaurar a sua função normal e a integridade estrutural após uma lesão, passando pelo processo de cicatrização. Quais são as 3 fases desse processo, em ordem cronológica, e suas respectivas características?', 'Fase reativa (proliferação e migração epitelial), fase de maturação (regeneração do tecido conjuntivo) e fase proliferativa (proliferação de colágeno e formação da cicatriz).', 'Fase inflamatória (hemostasia e quimiotaxia), fase proliferativa (regeneração do tecido conjuntivo) e fase de maturação (contração, formação e remodelamento da cicatriz).', 'Fase Inflamatória (hemostasia e inflamação), fase regenerativa (formação e contração da cicatriz) e fase de remodelagem (migração epitelial e proliferação/regeneração do tecido conjuntivo).', 'Fase de remodelagem (hemostasia e quimiotaxia), fase reativa (proliferação e migração epitelial) e fase maturacional (contração e formação da cicatriz).', 'Fase proliferativa (migração e proliferação epitelial), fase maturacional (contração formação da cicatriz) e fase reativa (hemostasia e quimiotaxia).', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Infectologia', 'media', 'Assinale a alternativa que apresenta 2 tipos de bactérias que estão entre as mais frequentemente encontradas/isoladas na apendicite aguda perfurada.', 'Acinetobacter baumanna e Klatsella pneumoniae.', 'Pseudomonas aeruginosa e Bacteroides coorosuis.', 'Escherichia coli e Bacteroides fragilis.', 'Campylobacter jejuni e Burkholderia capacia.', 'Acinetobacter baumanna e Escherichia coli.', 'C');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Anestesiologia', 'media', 'Em um paciente com doença coronariana, qual dos seguintes agentes NÃO seria indicado para indução anestésica, por ter como efeito colateral a hipertensão?', 'Tiopental.', 'Propofol.', 'Cetamina.', 'Etomidato.', 'Midazolam.', 'C');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Endocrinologia', 'facil', 'Um paciente será submetido a uma tireoidectomia total devido a um câncer de tireoide. Diante disso, as principais complicações que podem ocorrer após o procedimento e devem ser informadas ao paciente pelo médico são:', 'hipercalcemia e alteração da voz.', 'hipocalemia e rouquidão.', 'hipocalcemia e paresia dos músculos da face.', 'hipercalemia e dificuldade de deglutição.', 'hipocalcemia e alteração da voz.', 'E');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', NULL, 'media', 'Segundo a classificação de Caprini para pacientes cirúrgicos, assinale a alternativa correta quanto classificação de risco para TEV (Tromboembolismo Venoso) de um paciente de 54 anos que foi submetido a uma cirurgia de câncer de cólon, aberta, que durou aproximadamente 2h.', 'Risco muito baixo.', 'Risco baixo.', 'Risco moderado.', 'Risco alto.', 'Risco muito alto.', 'D');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Gastroenterologia', 'facil', 'Qual das seguintes alternativas apresenta a maior causa de obstrução do intestino delgado?', 'Hérnias.', 'Doença de Crohn.', 'Aderências.', 'Neoplasias.', 'Doenças neurológicas.', 'C');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Gastroenterologia', 'media', 'Um paciente de 65 anos apresenta dor, distensão abdominal e vômitos repetidos há 2 dias. Não evacua e não elimina flatos há 3 dias. Os exames de imagem mostram distensão de intestino delgado e fezes em reto. Assinale a alternativa que apresenta a melhor conduta inicial para tratamento desse paciente.', 'Coletar exames laboratoriais para detectar se há distúrbios hidroeletrolíticos e efetuar passagem de sonda nasogástrica para drenagem e hidratação.', 'Indicar laparotomia exploradora para melhor diagnosticar e tratar o paciente, já que ele apresenta o quadro há mais de 2 dias.', 'Coletar exames laboratoriais para detectar se há sinais de infecção associada; passar sonda nasoenteral para alimentação pós-pilórica e iniciar antibióticos de forma profilática.', 'Conversar com os familiares e indicar laparotomia exploradora com ileostomia associada, pois, nesses casos de distensão grande do delgado, não é recomendada anastomose primária.', 'Coletar exames laboratoriais; realizar tomografia para melhor avaliação e, a seguir, encaminhar o paciente para cirurgia, pois a maior parte desses casos é solucionada por meio de cirurgia.', 'A');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Cirurgia', 'Gastroenterologia', 'facil', 'Um paciente de 72 anos foi submetido a uma laparotomia exploradora por diverticulite complicada de cólon sigmoide, tendo sido realizada uma cirurgia com ressecção do sigmoide, fechamento do coto retal e confecção de colostomia terminal no cólon descendente. Esse tipo de cirurgia denomina-se', 'cirurgia de Whipple.', 'cirurgia de Hartmann.', 'cirurgia de Murphy.', 'cirurgia de Duhamel.', 'cirurgia de Wilson.', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Pediatria', 'Endocrinologia', 'facil', 'Assinale a alternativa correta sobre Diabetes na infância.', 'Diabetes na infância é uma condição muito rara abaixo dos 10 anos de idade.', 'Diabetes tipo I é a mais frequente na infância.', 'Diabetes do tipo gestacional é mais prevalente na pré-adolescência do que nas demais faixas etárias das mulheres.', 'Diabetes na infância acomete apenas meninos.', 'A resistência insulínica nos lactentes é de grande importância para a manutenção da glicemia.', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Pediatria', 'Endocrinologia', 'media', 'Menina de 11 anos apresenta peso de 39 Kg, altura de 144 cm e seu índice de massa corporal é de 23 Kg/m². Ela passou por consulta com dois médicos que prescreveram medicamentos "para emagrecer". Caso não haja outras complicações associadas, a conduta para esse caso deve ser', 'manter os medicamentos prescritos.', 'encaminhar para academia de ginástica e psicoterapia.', 'colher exames: hemograma, triglicerideos, colesterol e iniciar ansiolítico.', 'indicar tomografia de crânio para avaliação da sela túrcica e investigar cariótipo.', 'controlar ingesta calórica e oferecer oportunidade de exercicios físicos regulares.', 'A');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Pediatria', 'Gastroenterologia', 'media', 'A Intolerância à Lactose (IL) e a Alergia à Proteina do Leite de Vaca (APLV) possuem sinais e sintomas semelhantes, por isso a importância de avaliar a diferença em sua origem, sinais e sintomas. Sobre esse assunto, assinale a alternativa correta.', 'Na sua grande maioria, os casos de IL são associados a uma condição genética de pessoas de origem asiática.', 'Urticária, inchaço e vômito podem ser consequência da APLV.', 'A APLV é uma condição benigna que afeta apenas crianças e desaparece na adolescência.', 'Na IL, não são recomendados testes de tolerância à lactose e de hidrogênio no expirado, devido ao risco de insuficiência respiratória.', 'Na APLV, conduta será prescrever medicamentos antialérgicos ou anti-inflamatórios.', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Pediatria', 'Cirurgia', 'media', 'Um menino de dois anos tem uma pneumonia, com derrame pleural extenso, causada por estafilococo. Ele encontra-se acordado com sinais moderados de desconforto respiratório e com cateter nasal de oxigênio de 3L/min. Em decorrência do quadro, há necessidade de drenagem torácica e, ao preparar o material, o cirurgião passa orientações ao residente. Assinale a alternativa que apresenta a orientação correta repassada pelo cirurgião ao residente.', 'Não há necessidade de anestesia local, pois a ferida não permite ação do analgésico.', 'Quanto menor o calibre do dreno, melhor será a recuperação do paciente.', 'Em geral, a melhor conduta é apenas a punção de alívio.', 'As imagens de ultrassom podem guiar melhor a posição do dreno e, assim, alcançar áreas com abscessos fechados.', 'O paciente deve estar sob intubação mecânica para a drenagem.', 'D');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Pediatria', 'Hematologia', 'media', 'Em relação à Doença Falciforme, assinale a alternativa INCORRETA.', 'Não é indicado aconselhamento genético futuro, para evitar preocupações para a família.', 'As crises álgicas se iniciam antes de 12 meses em muitos casos.', 'A hidratação venosa está indicada no início do tratamento em caso de crises álgicas.', 'O alívio da dor não é alcançado com paracetamol nos casos com recidivas.', 'As complicações da perfusão são pouco importantes durante as crises álgicas.', 'A');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Pediatria', 'Ortopedia', 'facil', 'Um recém-nascido está sendo examinado pelo pediatra ainda no alojamento conjunto e, quando é realizada a flexão da coxa sobre o quadril, depois abdução e extensão da coxa, existe uma alteração do movimento sentida pelo examinador. Esse procedimento descrito denomina-se', 'teste de Manchester.', 'manobra de Ortolani.', 'exame de Denver.', 'prova de Adams.', 'teste de Dick.', 'B');

INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer) VALUES ('ENARE', 2024, 'Pediatria', 'Nefrologia', 'media', 'Uma criança de dois anos de idade teve, há 10 dias, um quadro diarreico. Foi internado há 48h, apresentando plaquetopenia, queda do hematocrito e insuficiência renal. Nesse caso, o diagnóstico é', 'síndrome hemolítica urêmica.', 'glomerulonefrite pós-estreptococica.', 'refluxo vesicoureteral.', 'síndrome nefrótica.', 'pielonefrite aguda.', 'A');

