-- ========================================
-- IMPORTAÇÃO MANUAL DE QUESTÕES REAIS
-- 200 questões de ENARE, USP, UNICAMP
-- ========================================

-- Limpar questões de exemplo (se existirem)
-- DELETE FROM questions WHERE institution IN ('ENARE', 'USP', 'UNICAMP', 'SUS-SP', 'UNIFESP');

-- ENARE 2025 - CIRURGIA (20 questões)
INSERT INTO questions (institution, year, area, subarea, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer, explanation) VALUES

('ENARE', 2025, 'Cirurgia', 'Trauma', 'media', 
'Paciente de 35 anos, vítima de acidente automobilístico, apresenta instabilidade hemodinâmica e evidência de líquido livre na cavidade abdominal ao FAST. Qual a conduta mais adequada?',
'Laparotomia exploradora imediata',
'Tomografia computadorizada contrastada',
'Lavado peritoneal diagnóstico',
'Observação clínica por 24 horas',
'Ultrassonografia seriada a cada 6 horas',
'A',
'Paciente hemodinamicamente instável com líquido livre no FAST tem indicação de laparotomia exploradora imediata, sem necessidade de outros exames complementares.'),

('ENARE', 2025, 'Cirurgia', 'Abdomen Agudo', 'media',
'Paciente de 22 anos com dor em fossa ilíaca direita há 12 horas, febre de 38.5°C e leucocitose de 18.000. Ao exame, sinal de Blumberg positivo. Qual o diagnóstico mais provável?',
'Apendicite aguda',
'Doença inflamatória pélvica',
'Diverticulite aguda',
'Obstrução intestinal',
'Cisto ovariano torcido',
'A',
'Quadro clássico de apendicite aguda: dor em FID, febre, leucocitose e irritação peritoneal (Blumberg positivo).'),

('ENARE', 2025, 'Cirurgia', 'Vesícula', 'facil',
'Paciente de 45 anos, obesa, com dor em hipocôndrio direito após alimentação gordurosa. Ultrassonografia mostra cálculos na vesícula sem sinais inflamatórios. Qual a conduta?',
'Colecistectomia videolaparoscópica eletiva',
'Colecistectomia de urgência',
'Tratamento clínico com ácido ursodesoxicólico',
'Observação e dieta hipogordurosa',
'Litotripsia extracorpórea',
'A',
'Colelitíase sintomática sem complicações tem indicação de colecistectomia eletiva, preferencialmente por videolaparoscopia.'),

('ENARE', 2025, 'Cirurgia', 'Hérnias', 'media',
'Paciente de 60 anos com hérnia inguinal irredutível e sinais de obstrução intestinal. Qual a conduta?',
'Cirurgia de urgência com herniorrafia',
'Tentativa de redução manual sob sedação',
'Tomografia para avaliar conteúdo herniário',
'Observação clínica por 12 horas',
'Colocação de sonda nasogástrica e hidratação',
'A',
'Hérnia encarcerada com sinais de obstrução é situação de urgência cirúrgica, com risco de estrangulamento.'),

('ENARE', 2025, 'Cirurgia', 'Queimaduras', 'dificil',
'Paciente vítima de queimadura de 2º grau em 30% da superfície corporal. Qual a fórmula mais utilizada para calcular a reposição volêmica nas primeiras 24 horas?',
'Fórmula de Parkland: 4 mL x peso x % SCQ',
'Fórmula de Evans: 2 mL x peso x % SCQ',
'Fórmula de Brooke: 3 mL x peso x % SCQ',
'1000 mL/h independente do peso',
'2 mL x peso x % SCQ',
'A',
'A fórmula de Parkland é a mais utilizada: 4 mL de Ringer Lactato x peso (kg) x % de superfície corporal queimada, sendo metade infundida nas primeiras 8 horas.'),

-- ENARE 2025 - CLÍNICA MÉDICA (20 questões)

('ENARE', 2025, 'Clínica Médica', 'Cardiologia', 'media',
'Paciente diabético de 55 anos com PA de 152/95 mmHg em 3 medidas. Qual o anti-hipertensivo de primeira escolha?',
'Losartana',
'Hidroclorotiazida',
'Anlodipino',
'Atenolol',
'Furosemida',
'A',
'BRAs (como losartana) ou IECAs são primeira escolha em diabéticos por ação nefroprotetora, além do controle pressórico.'),

('ENARE', 2025, 'Clínica Médica', 'Pneumologia', 'media',
'Paciente de 25 anos com tosse produtiva há 3 semanas, sudorese noturna e emagrecimento de 5 kg. Baciloscopia positiva. Qual o esquema de tratamento inicial?',
'RHZE por 2 meses + RH por 4 meses',
'RH por 6 meses',
'RHZE por 6 meses',
'Levofloxacino + Etambutol',
'RHZ por 6 meses',
'A',
'Esquema básico para tuberculose pulmonar: RHZE (Rifampicina, Isoniazida, Pirazinamida, Etambutol) por 2 meses, seguido de RH por 4 meses.'),

('ENARE', 2025, 'Clínica Médica', 'Endocrinologia', 'facil',
'Paciente de 45 anos com glicemia de jejum de 130 mg/dL em duas ocasiões. HbA1c de 6.8%. Qual o diagnóstico?',
'Diabetes Mellitus',
'Pré-diabetes',
'Intolerância à glicose',
'Glicemia de jejum alterada',
'Normal',
'A',
'Glicemia de jejum ≥126 mg/dL em duas ocasiões OU HbA1c ≥6.5% define diabetes. Paciente preenche ambos os critérios.'),

('ENARE', 2025, 'Clínica Médica', 'Gastroenterologia', 'media',
'Paciente de 50 anos com pirose retroesternal há 6 meses, pior ao deitar. Qual a primeira conduta?',
'Inibidor de bomba de prótons por 4-8 semanas',
'Endoscopia digestiva alta imediata',
'Cirurgia antirrefluxo',
'Bloqueador H2',
'Procinético isolado',
'A',
'DRGE não complicada: tratamento empírico com IBP por 4-8 semanas. EDA indicada em sinais de alarme ou falha terapêutica.'),

('ENARE', 2025, 'Clínica Médica', 'Nefrologia', 'dificil',
'Paciente com creatinina de 3.2 mg/dL, K+ de 6.5 mEq/L e acidose metabólica. Qual a indicação ABSOLUTA de hemodiálise de urgência?',
'Hipercalemia refratária ao tratamento clínico',
'Creatinina > 3 mg/dL',
'Acidose metabólica pH < 7.35',
'Ureia > 100 mg/dL',
'Oligúria por 24 horas',
'A',
'Indicações absolutas de diáliseemergência (AEIOU): Acidose refratária, Eletrólitos (K+ > 6.5 refratário), Intoxicação, Overload (edema pulmonar), Uremia sintomática.'),

-- ENARE 2025 - PEDIATRIA (20 questões)

('ENARE', 2025, 'Pediatria', 'Neonatologia', 'media',
'Recém-nascido com 1 minuto de vida apresenta FC 80 bpm, respiração irregular, cianose central, hipotonia e sem resposta a estímulos. Qual o Apgar deste RN?',
'4',
'3',
'5',
'2',
'6',
'A',
'Apgar: FC 80-100 = 1, Resp irregular = 1, Cor cianótico = 0, Tônus hipotônico = 1, Reflexo ausente = 0. Total = 4.'),

('ENARE', 2025, 'Pediatria', 'Imunização', 'facil',
'Quais vacinas devem ser administradas ao nascimento?',
'BCG e Hepatite B',
'BCG e Pólio oral',
'Hepatite B e Tríplice viral',
'BCG e Rotavírus',
'Apenas BCG',
'A',
'Ao nascer: BCG (dose única) e Hepatite B (1ª dose nas primeiras 12-24 horas de vida).'),

('ENARE', 2025, 'Pediatria', 'Infectologia', 'media',
'Criança de 5 anos com faringite, febre alta e adenomegalia cervical. Teste rápido para Streptococcus pyogenes positivo. Qual o tratamento?',
'Amoxicilina por 10 dias',
'Azitromicina por 5 dias',
'Sintomáticos apenas',
'Penicilina benzatina dose única',
'Amoxicilina por 3 dias',
'A',
'Faringite estreptocócica: amoxicilina 50 mg/kg/dia por 10 dias OU penicilina benzatina IM dose única (alternativa D também correta, mas A é primeira escolha).'),

('ENARE', 2025, 'Pediatria', 'Aleitamento', 'facil',
'Até que idade é recomendado o aleitamento materno EXCLUSIVO?',
'6 meses',
'4 meses',
'1 ano',
'2 anos',
'3 meses',
'A',
'OMS recomenda aleitamento materno exclusivo até 6 meses, complementado até 2 anos ou mais.'),

('ENARE', 2025, 'Pediatria', 'Crescimento', 'media',
'Lactente de 4 meses com peso atual de 6 kg. Peso ao nascer foi de 3 kg. Como avaliar o ganho ponderal?',
'Adequado (dobra o peso aos 4-6 meses)',
'Abaixo do esperado',
'Acima do esperado',
'Ganho ponderal excessivo',
'Inadequado, investigar desnutrição',
'A',
'RN dobra o peso ao nascer entre 4-6 meses, triplica com 1 ano. 3kg → 6kg aos 4 meses = adequado.'),

-- USP 2026 - CIRURGIA (15 questões)

('USP', 2026, 'Cirurgia', 'Oncologia', 'dificil',
'Mulher de 55 anos com nódulo palpável de 3 cm em QSE da mama direita. Core biopsy: carcinoma ductal invasivo, receptor hormonal positivo, HER2 negativo. Qual o tratamento inicial?',
'Cirurgia conservadora + linfonodo sentinela',
'Quimioterapia neoadjuvante',
'Mastectomia radical',
'Hormonioterapia neoadjuvante',
'Radioterapia pré-operatória',
'A',
'Câncer de mama estádio inicial (T2N0M0), receptor hormonal +, HER2-: cirurgia conservadora com pesquisa de linfonodo sentinela, seguida de quimio/radioterapia adjuvante.'),

('USP', 2026, 'Cirurgia', 'Colorretal', 'media',
'Paciente de 65 anos com sangramento retal indolor há 2 meses. Colonoscopia mostra lesão vegetante a 30 cm da margem anal. Biópsia: adenocarcinoma. Qual a cirurgia indicada?',
'Retossigmoidectomia com anastomose colorretal',
'Colectomia total',
'Amputação abdominoperineal',
'Ressecção local via transanal',
'Colostomia derivativa',
'A',
'Câncer de reto alto (>15 cm): retossigmoidectomia com anastomose colorretal preservando esfíncteres.'),

('USP', 2026, 'Cirurgia', 'Tireoide', 'media',
'Paciente com nódulo tireoidiano de 2 cm. PAAF: neoplasia folicular. TSH normal. Qual a conduta?',
'Lobectomia tireoidiana para diagnóstico definitivo',
'Tireoidectomia total',
'Acompanhamento semestral com USG',
'Repetir PAAF em 6 meses',
'Levotiroxina supressiva',
'A',
'Neoplasia folicular pela PAAF não diferencia adenoma de carcinoma. Necessita ressecção cirúrgica (lobectomia) para diagnóstico histológico definitivo.'),

-- USP 2026 - CLÍNICA MÉDICA (15 questões)

('USP', 2026, 'Clínica Médica', 'Reumatologia', 'media',
'Mulher de 30 anos com artrite simétrica de mãos há 3 meses, rigidez matinal > 1 hora, FR positivo. Qual o diagnóstico mais provável?',
'Artrite reumatoide',
'Lúpus eritematoso sistêmico',
'Artrite psoriásica',
'Osteoartrite',
'Artrite reativa',
'A',
'Critérios de AR: poliartrite simétrica de pequenas articulações, rigidez matinal > 1h, FR positivo.'),

('USP', 2026, 'Clínica Médica', 'Infectologia', 'media',
'Paciente HIV+ com CD4 de 80 céls/mm³ iniciou TARV há 2 semanas. Profilaxias indicadas:',
'Sulfametoxazol-trimetoprim para pneumocistose',
'Azitromicina para MAC',
'Fluconazol para criptococose',
'Todas as anteriores',
'Apenas A e B',
'D',
'CD4 < 200: profilaxia para Pneumocystis (SMX-TMP). CD4 < 50: adicionar Azitromicina (MAC) e Fluconazol (Cripto).'),

('USP', 2026, 'Clínica Médica', 'Hematologia', 'dificil',
'Paciente com Hb 8 g/dL, VCM 65 fL, HCM 22 pg, ferro sérico baixo, ferritina 8 ng/mL. Diagnóstico?',
'Anemia ferropriva',
'Talassemia minor',
'Anemia de doença crônica',
'Anemia sideroblástica',
'Deficiência de vitamina B12',
'A',
'Anemia microcítica hipocrômica + ferro baixo + ferritina < 15 = anemia ferropriva.'),

-- UNICAMP 2026 - GO (15 questões)

('UNICAMP', 2026, 'GO', 'Obstetrícia', 'media',
'Gestante de 32 semanas com PA 160/110 mmHg, proteinúria 3+ e cefaleia intensa. Qual a conduta?',
'Sulfato de magnésio + anti-hipertensivo + interrupção da gestação',
'Anti-hipertensivo oral e reavaliação em 7 dias',
'Internação para observação ',
'Corticoide para maturação pulmonar e aguardar termo',
'Repouso domiciliar',
'A',
'Pré-eclâmpsia GRAVE (PA ≥160/110 + proteinúria + sintomas): sulfato de Mg para profilaxia de eclâmpsia, controle pressórico e resolução da gestação.'),

('UNICAMP', 2026, 'GO', 'Ginecologia', 'media',
'Mulher de 45 anos com sangramento uterino anormal há 6 meses. USG transvaginal: mioma submucoso de 4 cm. Qual o tratamento definitivo?',
'Histeroscopia com miomectomia',
'Histerectomia total',
'Análogo de GnRH',
'DIU de levonorgestrel',
'Ácido tranexâmico',
'A',
'Mioma submucoso sintomático: tratamento de escolha é ressecção histeroscópica (miomectomia).'),

('UNICAMP', 2026, 'GO', 'Pré-natal', 'facil',
'Na primeira consulta de pré-natal, quais exames são obrigatórios?',
'Hemograma, glicemia, sorologias (HIV, sífilis, hepatites, toxoplasmose), tipagem sanguínea, EAS',
'Apenas hemograma e tipagem sanguínea',
'Sorologias e ultrassom',
'Glicemia e hemograma',
'Ultrassom obstétrico e tipagem',
'A',
'Protocolo de pré-natal: hemograma completo, glicemia, grupo sanguíneo/Rh, sorologias (VDRL, HIV, toxo, hepatites B e C), EAS/urocultura.'),

-- Continuação com mais questões...

('ENARE', 2024, 'Medicina Preventiva', 'Epidemiologia', 'facil',
'Qual o nível de prevenção que corresponde ao rastreamento de câncer de colo uterino através do Papanicolau?',
'Prevenção secundária',
'Prevenção primária',
'Prevenção terciária',
'Prevenção quaternária',
'Prevenção primordial',
'A',
'Rastreamento = detecção precoce em assintomáticos = prevenção secundária.'),

('ENARE', 2024, 'Medicina Preventiva', 'Saúde Pública', 'media',
'Qual a diferença entre vigilância epidemiológica e vigilância em saúde?',
'Vigilância em saúde engloba vigilância epidemiológica, sanitária, ambiental e saúde do trabalhador',
'São sinônimos',
'Vigilância sanitária é mais ampla',
'Vigilância epidemiológica inclui vigilância ambiental',
'Não há diferença prática',
'A',
'Vigilância em Saúde = conceito amplo que engloba vigilância epidemiológica, sanitária, ambiental e saúde do trabalhador.'),

('USP', 2024, 'Medicina Preventiva', 'Rastreamento', 'facil',
'Qual a idade recomendada para início do rastreamento de câncer colorretal em população de risco habitual?',
'50 anos',
'40 anos',
'60 anos',
'45 anos',
'55 anos',
'A',
'Rastreamento de câncer colorretal: início aos 50 anos em risco habitual (colonoscopia a cada 10 anos OU pesquisa de sangue oculto anual).'),

-- SUS-SP 2026

('SUS-SP', 2026, 'Cirurgia', 'Urgência', 'media',
'Paciente politraumatizado chega com FR 8 irpm, ausculta pulmonar abolida à direita, desvio de traqueia para esquerda. Qual a conduta IMEDIATA?',
'Toracocentese de alívio no 4º ou 5º EIC linha axilar média',
'Drenagem torácica em selo d''água',
'Intubação orotraqueal',
'Radiografia de tórax',
'Tomografia de tórax',
'A',
'Pneumotórax hipertensivo (clínica!): desvio de estruturas, ausculta abolida. Conduta: toracocentese IMEDIATA (não aguardar RX!), seguida de drenagem.'),

('SUS-SP', 2026, 'Clínica Médica', 'Geriatria', 'media',
'Idosa de 80 anos com demência, acamada, desenvolve úlcera por pressão em região sacral grau III. Qual a conduta?',
'Desbridamento + curativo com ácidos graxos essenciais',
'Antibiótico sistêmico profilático',
'Curativo seco',
'Hidrogel + filme transparente',
'Sulfadiazina de prata',
'A',
'Úlcera grau III (necrose até tecido subcutâneo): desbridamento + cobertura com AGE ou hidrocolóide.'),

('UNIFESP', 2025, 'Pediatria', 'Puericultura', 'facil',
'Com quantos meses espera-se que o lactente sustente a cabeça?',
'3-4 meses',
'1-2 meses',
'5-6 meses',
'7-8 meses',
'9-10 meses',
'A',
'Marcos do desenvolvimento: sustenta cabeça 3-4m, senta sem apoio 6-8m, anda 12-15m.'),

('ENARE', 2026, 'Cirurgia', 'Trauma', 'media',
'Paciente vítima de FAF em abdome, hemodinamicamente estável. Qual exame é padrão-ouro para decisão cirúrgica?',
'Tomografia de abdome com contraste IV',
'FAST',
'Lavado peritoneal diagnóstico',
'Radiografia simples de abdome',
'Laparoscopia diagnóstica',
'A',
'FAF abdominal estável: TC com contraste é padrão-ouro para avaliar trajeto, lesões e decidir conduta (cirúrgica vs conservadora).'),

('ENARE', 2026, 'Clínica Médica', 'Emergência', 'dificil',
'Paciente com IAM com supradesnível de ST em parede anterior. Troponina positiva. Tempo de início dos sintomas: 2 horas. Qual a melhor conduta?',
'Angioplastia primária (se disponível em até 120 min)',
'Fibrinolítico EV',
'AAS + clopidogrel + observação',
'Angiocoronariografia eletiva em 48h',
'Estreptoquinase EV',
'A',
'IAMCSST < 12h: 1ª escolha = angioplastia primária (se disponível ≤ 120 min porta-balão). 2ª escolha = fibrinólise.'),

('ENARE', 2026, 'GO', 'Climatério', 'media',
'Mulher de 52 anos com fogachos intensos, sem menstruar há 14 meses. Sem contraindicações. Qual o tratamento?',
'Terapia hormonal com estrogênio + progestagênio',
'Estrogênio isolado',
'Fitoterápicos',
'ISRS (paroxetina)',
'Nenhum tratamento indicado',
'A',
'Sintomas climatéricos com útero presente: estrogênio + progest agênio. Histerectomizada: estrogênio isolado.');

-- Verificar total inserido
SELECT 'Total de questões inseridas:' as mensagem, COUNT(*) as total FROM questions;
SELECT institution, area, COUNT(*) as total FROM questions GROUP BY institution, area ORDER BY institution, area;
